### ISSUE TITLE
Instalar pacotes Composer no entrypoint 

### ISSUE THREAD

**Issue by lhsazevedo** [PHPRio/novo-site#12]
Atualmente o entrypoint não executa o comando `composer install` para instalar as dependências do projeto, resultando no seguinte erro ao subir o container:

```
novo-site-backend-1  | Could not open input file: /var/www/html/vendor/bin/jigsaw
```

**Comment by vitormattos** [comment]
Algo tipo isto no entrypoint resolve:
```bash
if [ ! -d "vendor" ]; then
    composer install
fi
```
